<?php

namespace JuanchoSL\HttpHeaders\Constants\FtpCodes;

class Codes
{
    const RESTART_MARKER_REPLAY = 110;
    const SERVICE_READY_IN_NNN_MINUTES = 120;
    const DATA_CONNECTION_ALREADY_OPEN = 125;
    const FILE_STATUS_OKAY = 150;
    const COMMAND_NOT_IMPLEMENTED_SUPERFLUOUS = 202;
    const SYSTEM_STATUS = 211;
    const DIRECTORY_STATUS = 212;
    const FILE_STATUS = 213;
    const HELP_MESSAGE = 214;
    const NAME_SYSTEM_TYPE = 215;
    const SERVICE_READY_FOR_NEW_USER = 220;
    const SERVICE_CLOSING_CONTROL_CONNECTION = 221;
    const DATA_CONNECTION_OPEN = 225;
    const CLOSING_DATA_CONNECTION = 226;
    const ENTERING_PASSIVE_MODE = 227;
    const ENTERING_LONG_PASSIVE_MODE = 228;
    const ENTERING_EXTENDED_PASSIVE_MODE = 229;
    const USER_LOGGED_IN_PROCEED = 230;
    const USER_LOGGED_IN_AUTHORIZED = 232;
    const SERVER_ACCEPTS_MO_SECURITY_MECHANISM_SPECIFIED_BY_THE_CLIENT = 234;
    const SERVER_ACCEPTS_NO_SECURITY_DATA_GIVEN_BY_THE_CLIENT = 235;
    const REQUESTED_FILE_ACTION_WAS_OKAY = 250;
    const USER_NAME_OKAY = 331;
    const NO_NEED_ACCOUNT_FOR_LOGIN = 332;
    const SERVER_ACCEPTS_THE_SECURITY_MECHANISM_SPECIFIED_BY_THE_CLIENT = 334;
    const SERVER_ACCEPTS_THE_SECURITY_DATA_GIVEN_BY_THE_CLIENT = 335;
    const USERNAME_OKAY = 336;
    const SERVICE_NOT_AVAILABLE = 421;
    const CANT_OPEN_DATA_CONNECTION = 425;
    const CONNECTION_CLOSED = 426;
    const INVALID_USERNAME_OR_PASSWORD = 430;
    const NEED_SOME_UNAVAILABLE_RESOURCE_TO_PROCESS_SECURITY = 431;
    const REQUESTED_HOST_UNAVAILABLE = 434;
    const REQUESTED_FILE_ACTION_NOT_TAKEN = 450;
    const REQUESTED_ACTION_ABORTED = 451;
    const REQUESTED_ACTION_NOT_TAKEN = 452;
    const SYNTAX_ERROR_IN_PARAMETERS_OR_ARGUMENTS = 501;
    const COMMAND_NOT_IMPLEMENTED = 502;
    const BAD_SEQUENCE_OF_COMMANDS = 503;
    const COMMAND_NOT_IMPLEMENTED_FOR_THAT_PARAMETER = 504;
    const NOT_LOGGED_IN = 530;
    const NEED_ACCOUNT_FOR_STORING_FILES = 532;
    const COMMAND_PROTECTION_LEVEL_DENIED_FOR_POLICY_REASONS = 533;
    const REQUEST_DENIED_FOR_POLICY_REASONS = 534;
    const FAILED_SECURITY_CHECK = 535;
    const DATA_PROTECTION_LEVEL_NOT_SUPPORTED_BY_SECURITY_MECHANISM = 536;
    const COMMAND_PROTECTION_LEVEL_NOT_SUPPORTED_BY_SECURITY_MECHANISM = 537;
    const FILE_UNAVAILABLE = 550;
    const PAGE_TYPE_UNKNOWN = 551;
    const REQUESTED_FILE_ACTION_ABORTED = 552;
    const FILE_NAME_NOT_ALLOWED = 553;
    const INTEGRITY_PROTECTED_REPLY = 631;
    const CONFIDENTIALITY_AND_INTEGRITY_PROTECTED_REPLY = 632;
    const CONFIDENTIALITY_PROTECTED_REPLY = 633;
}